services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookstore
      - JWT_SECRET=your-secret-key
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ./wait-for-it.sh db:5432 -- npm run start:dev


  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
